CREATE TABLE IF NOT EXISTS clientes (
id SERIAL PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
telefone VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
servico VARCHAR(255) NOT NULL,
dataCadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
